### Site metadata ###

site_name: shacled
site_description: shacled - SHACL editor etc
#site_url: https://GeiselSoftware.github.io/shacled/

repo_url: https://github.com/GeiselSoftware/shacled
edit_uri: edit/main/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Index: index.md
  - Backends: backends.md
  - Addendum: addendum.md
  - About MkDocs: about-mkdocs.md

markdown_extensions:
  - toc:
      permalink: True
      baselevel: 2
      separator: "_"

  
