site_name: KGM
site_url: http://h1:8001/kgm
theme:
  name: material
  features:
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - docs/abbreviations.md
  - abbr
  - attr_list

# Page tree
nav:
  - KG for practical software engeneering: kgm-introduction.md
  - KGM - Used Guide: kgm-userguide.md
  - Backends: backends.md
  - mkdocs-material: about-mkdocs.md
  - Addendum: addendum.md
