site_name: KGM
site_url: http://h1:8001/kgm
theme:
  name: material
  features:
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - KG for practical software engeneering: kgm-introduction.md
  - KGM - Used Guide: kgm-userguide.md
  - Backends: backends.md
  - mkdocs-material: about-mkdocs.md
  - Addendum: addendum.md

plugins:
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin/blob/master/README.md
  
markdown_extensions:
  - keyword_linker:
      words:
        RDF: https://www.w3.org/TR/rdf12-turtle/
        SPARQL: https://www.w3.org/TR/rdf-sparql-query/
        URI: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
        CURIE: https://www.w3.org/TR/2010/NOTE-curie-20101216/


